### ISSUE TITLE
[1주차]  Mine 애플리케이션 진행 

### ISSUE THREAD

**Issue by seong-dodo** [CodeSoom/project-react-4-seong-dodo#1]
##### 4주 프로젝트 (2021.6/28~2021.7/25)

#  🐜  Mine 애플리케이션 

## 1. 이 앱은 언제 사용 하나요?
자산 관리 애플리케이션으로 자산 관리에 관심을 가지고 있는 사용자라면 가계부 작성을 기반으로 나의 것을 지키는 습관을 만들어주는 서비스를 제공하고 더 나아가 자산 관리에 도움이 되는 정보 제공함으로써 자산 관리의 니즈가 있는 사용자라면 누구나 사용할 수 있습니다.

## 2. 구체적인 사례는 무엇인가요?
> 홈 Page

![image](https://user-images.githubusercontent.com/68280407/123620485-3fd1f700-d845-11eb-96bd-786ebbdc773d.png)
> 예산 Page

![image](https://user-images.githubusercontent.com/68280407/123620577-5b3d0200-d845-11eb-9d41-b5a6d0d814cd.png)
> 캘린더 Page

![image](https://user-images.githubusercontent.com/68280407/123620677-73ad1c80-d845-11eb-8526-e6394360fcb0.png)

## 3. 이번 주가 지나면 사용자는 무엇을 할 수 있나요?
✔️  Mine 애플리케이션 홈페이지 화면에서 예산 설정 페이지와 가계부 작성 페이지로 이동할 수 있다.
✔️ 예산 설정 페이지로 이동하면 사용자는 한 달 예산을 입력할 수 있다.

###  🏊 [1주차] 6월28일(월) - 7월4일(일) 
1.  사용자는 홈페이지에서 예산 설정 페이지와 가계부 작성 페이지로 이동한다.
 - [ ] 홈페이지 컴포넌트 개발한다.
 - [ ] 가계부 컴포넌트, 예산 설정 컴포넌트 라우팅 추가한다.
2.  사용자는 한 달 예산을 입력할 수 있다.
 - [ ]  예산 입력 input 기능 개발한다.
 - [ ] 예산 입력 컴포넌트 개발한다.
 - [ ] 예산 입력 데이터 스키마를 정의한다.

3. 사용자는 하단 내비게이션 탭에서 홈, 달력, 예산 페이지로 이동할 수 있다.
  - [ ] 홈, 달력, 예산 페이지 이동 링크 추가한다.
4. 사용자는 상단 탭 화면을 확인 할 수 있다.

**Comment by moonkii** [comment]
화면은 직접 디자인하신건가요?
화면 이미지를 첨부해 주셔서 훨씬 이해하기가 좋은 것 같아요 👍 
개인 프로젝트는 배포전까지는 트레이너가 직접 확인하기가 어렵기 때문에 이렇게 이미지로 설명해주시면 리뷰에도 많이 도움이 돼요

![image](https://user-images.githubusercontent.com/46776329/123838667-316c0400-d947-11eb-89b9-0f89e77e57b9.png)

만약 계획하신 기능구현이 모두 가능하다면 문제가 없겠지만,
만약 시간이 부족하다고 하면 홈페이지를 보여주는 것과 에산을 보여주는 것 중 어떤게 더 핵심기능이고, 우선순위가 높나요?
항상 핵심 기능을 먼저 구현하도록 계획을 세우시면 좋아요!

1주일 단위로 서비스를 배포한다고 생각하시고 프로젝트를 진행하시면 좋아요.
이번주 작업이 모두 끝나면 서비스를 배포하고 사람들의 피드백을 받을 수 있게 해보세요.
그러면 프로젝트의 방향성을 잡기도 더욱 쉬울거에요!

**Comment by seong-dodo** [comment]
네~ 감사합니다 😄 

> 홈페이지를 보여주는 것과 에산을 보여주는 것 중 어떤게 더 핵심기능이고, 우선순위가 높나요?

#4 : 진행 상황 이슈 등록 하였습니다. 말씀해주신대로 작업단위를 작게 나눠서 진행하겠습니다!
