### ISSUE TITLE
[2주차] 상단 탭 월 이동 기능 개발

### ISSUE THREAD

**Issue by seong-dodo** [CodeSoom/project-react-4-seong-dodo#15]
##### 4주 프로젝트 (2021.6/28~2021.7/25)
# 🐜 Mine 애플리케이션

## 1. 이번 주가 지나면 사용자는 무엇을 할 수 있나요?
**1주차 추가 기능**
✔️ Mine 애플리케이션 홈페이지 화면에서 예산 설정 페이지와 가계부 작성 페이지로 이동할 수 있다.
✔️ 예산 설정 페이지로 이동하면 사용자는 한 달 예산을 입력할 수 있다.

**2주차 추가 기능**
✔️ 달력 화면을 확인 할 수 있다.
✔️ 상단 탭에서 이전 달 , 다음 달로 이동을 할 수 있다.

### 🏊 [2주차] 7월5일(월) - 7월11일(일)

1. **사용자는 상단 탭에서 이전 달, 다음 달로 이동을 할 수 있다.**
- [ ] 월 이동 기능 개발을 추가한다. 

2. 사용자는 달력 페이지에서 달력 화면을 확인 할 수 있다.
- [ ] 달력 화면을 그려낸다.
- [ ] 달력 데이터 스키마를 정의한다.

**Comment by Kihyun92** [comment]
혹시 배포가 됐을까요? 확인할 수 있는 url을 리드미에 추가해주셔도 좋을 것 같네요 :)

**Comment by seong-dodo** [comment]
안녕하세요~
배포하는 방법을 아직 숙지하지 못해서 미진행 상황입니다. 
배포 후 말씀하신대로 url을 리드미에 추가하겠습니다^~~~~^ 
감사합니다 😄😄😄😄😄
