### ISSUE TITLE
[1주차] Mine 프로젝트 개발 환경 구축

### ISSUE THREAD

**Issue by seong-dodo** [CodeSoom/project-react-4-seong-dodo#2]
## React 개발 환경 구축
- NPM 설치 및 의존성 추가
- Webpack Dev Server 설치
- ESLint 설치 및 설정
- Babel 설치
- 리액트 설치
- Jest & React testing library 설치
- Redux & Redux Thunk 설치
- React Router 설치

**Comment by moonkii** [comment]
작업 단위는 가능한 작게 쪼개는게 좋아요.
Redux 는 당장 필요한가요?
당장 리액트 라우터가 필요한가요?
가능한 작업을 작게하기 위해서 필요할 때 필요한 것들을 추가하시면 좋아요.
