### ISSUE TITLE
[3주차] 내역 추가 버튼 기능 개발

### ISSUE THREAD

**Issue by seong-dodo** [CodeSoom/project-react-4-seong-dodo#28]
##### 4주 프로젝트 (2021.6/28~2021.7/25)
# 🐜 Mine 애플리케이션

## 내역 추가 버튼 기능 개발
1. 사용자는 내역 추가 버튼을 클릭하면 내역 추가 상세 모달 창을 확인 할 수 있다.

- [ ]  버튼 클릭 기능을 추가한다.
- [ ] 내역 추가 상세페이지 모달창을 생성한다.

**Comment by moonkii** [comment]
모달창을 사용할 때 발생할 수 있는 상황이나 예외처리 같은 것들은 어떤게 있을까요?
미리 고민해보면 좋을 것 같아요.

**Comment by seong-dodo** [comment]
넵!!! 감사합니다!! 말씀해주신 부분도 고민해보겠습니다. 고민해보고 어려우면 도움 요청 드리겠습니다 ~~~~

**Comment by seong-dodo** [comment]
https://github.com/CodeSoom/project-react-4-seong-dodo/issues/28#issuecomment-878351207

안녕하세요. 모달창을 사용할 때 발생할 수 있는 상황이나 예외처리가 어떤 것들이 있는지 여쭤봐도 될까요??
이부분에 대해 고민해보았는데, 어떤 부분을 말씀하시는지 감을 못잡아서 문의드립니다... 🙏
