### ISSUE TITLE
[1주차] 하단 내비게이션 탭 기능 개발

### ISSUE THREAD

**Issue by seong-dodo** [CodeSoom/project-react-4-seong-dodo#8]
##### 4주 프로젝트 (2021.6/28~2021.7/25)
# 🐜 Mine 애플리케이션
## 하단 내비게이션 탭 기능 개발
**1주차** 

추가 기능 3. 사용자는 하단 내비게이션 탭에서 홈, 달력, 예산 페이지로 이동할 수 있다.
- [ ] 홈 페이지 이동 링크 추가
- [ ] 달력 페이지 이동 링크 추가
- [ ] 예산 페이지 이동 링크 추가

**Comment by moonkii** [comment]
괜찮다면 주차 별로 하나의 이슈로 관리해주면 좋을 것 같아요.
